### ISSUE TITLE
求问

### ISSUE THREAD

**Issue by piesharan** [skyonedot/keepGreen#1]
您好，我看您之前有运行过github上一个叫Galaxylearning的项目，请问能告知一下如何运行吗

**Comment by skyonedot** [comment]
我记得我没运行起来.. 报错了好多, 我就放弃了👀

**Comment by piesharan** [comment]
噢噢好的，非常谢谢您能回我，祝您生活愉快




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "s1119858711/keepGreen"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月20日(星期天) 晚上10:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [s1119858711/keepGreen] 求问 (Issue #1)





 
我记得我没运行起来.. 报错了好多, 我就放弃了👀
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by skyonedot** [comment]
好的好的
